/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChooseTh: typeof import('./components/table/ChooseTh.vue')['default']
    Column: typeof import('./components/table/Column.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Index: typeof import('./components/form/Index.vue')['default']
    MButton: typeof import('./components/MButton.vue')['default']
    MCheckboxGroup: typeof import('./components/form/MCheckboxGroup.vue')['default']
    MDate: typeof import('./components/form/MDate.vue')['default']
    MDateTime: typeof import('./components/form/MDateTime.vue')['default']
    MDateTimeRange: typeof import('./components/form/MDateTimeRange.vue')['default']
    MFormItem: typeof import('./components/form/MFormItem.vue')['default']
    MInput: typeof import('./components/form/MInput.vue')['default']
    MRadioGroup: typeof import('./components/form/MRadioGroup.vue')['default']
    MSelect: typeof import('./components/form/MSelect.vue')['default']
    Organization: typeof import('./components/Organization.vue')['default']
    Pagination: typeof import('./components/table/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
